#ifndef _LCOM_ASSETS_FONT_H_
#define _LCOM_ASSETS_FONT_H_

#include "a.xpm"
#include "B.xpm"
// #include "b.xpm"
// #include "c.xpm"
#include "d.xpm"
#include "e.xpm"
// #include "f.xpm"
// #include "g.xpm"
// #include "h.xpm"
// #include "i.xpm"
// #include "j.xpm"
// #include "k.xpm"
#include "l.xpm"
// #include "m.xpm"
// #include "n.xpm"
#include "o.xpm"
// #include "p.xpm"
// #include "q.xpm"
// #include "r.xpm"
#include "s.xpm"
#include "t.xpm"
// #include "u.xpm"
// #include "v.xpm"
// #include "w.xpm"
// #include "x.xpm"
// #include "y.xpm"
// #include "z.xpm"

#include "0.xpm"
#include "1.xpm"
#include "2.xpm"
#include "3.xpm"
#include "4.xpm"
#include "5.xpm"
#include "6.xpm"
#include "7.xpm"
#include "8.xpm"
#include "9.xpm"

#include "twodots.xpm"

#endif
